/**
 * RLS migration generator — docs/30-architecture/01-MULTI-TENANCY.md §3
 *
 * Reads prisma/schema.prisma, finds every model that has a `tenantId` column and emits SQL that:
 *   1. ENABLE + FORCE ROW LEVEL SECURITY
 *   2. creates policy `tenant_isolation` (USING + WITH CHECK on app.current_tenant_id GUC)
 *   3. GRANTs DML to `app_user`
 * Platform tables (no tenantId) get explicit, minimal grants.
 *
 * Idempotent: policies are dropped/re-created, so it can run in every migration that adds tables.
 *
 * Usage: pnpm tsx scripts/gen-rls.ts > prisma/migrations/<ts>_rls/migration.sql
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const schema = readFileSync(resolve(process.cwd(), "prisma/schema.prisma"), "utf8");
const modelRe = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;

const tenantTables: string[] = [];
const platformTables: string[] = [];
for (const m of schema.matchAll(modelRe)) {
  const [, name, body] = m;
  if (!name || !body) continue;
  const mapped = body.match(/@@map\("([^"]+)"\)/)?.[1];
  const table = mapped ?? name;
  if (/^\s+tenantId\s+String(?!\?)/m.test(body)) tenantTables.push(table);
  else platformTables.push(table);
}

const APP_ROLE = "app_user";
const out: string[] = [];
out.push(`-- Generated by scripts/gen-rls.ts — DO NOT EDIT BY HAND`);
out.push(`-- Tenant-scoped tables: ${tenantTables.length} · Platform tables: ${platformTables.length}`);
out.push(``);
out.push(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN`);
out.push(`  CREATE ROLE ${APP_ROLE} LOGIN PASSWORD '${APP_ROLE}' NOBYPASSRLS; END IF; END $$;`);
out.push(`GRANT USAGE ON SCHEMA public TO ${APP_ROLE};`);
out.push(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${APP_ROLE};`);
out.push(``);

for (const t of tenantTables) {
  out.push(`-- ${t}`);
  out.push(`ALTER TABLE "${t}" ENABLE ROW LEVEL SECURITY;`);
  out.push(`ALTER TABLE "${t}" FORCE ROW LEVEL SECURITY;`);
  out.push(`DROP POLICY IF EXISTS tenant_isolation ON "${t}";`);
  out.push(`CREATE POLICY tenant_isolation ON "${t}"`);
  out.push(`  USING ("tenantId" = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid)`);
  out.push(`  WITH CHECK ("tenantId" = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);`);
  out.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON "${t}" TO ${APP_ROLE};`);
  out.push(``);
}

out.push(`-- Platform tables: minimal grants for the runtime role`);
const platformGrants: Record<string, string> = {
  Tenant: "SELECT", // host → tenant resolution
  TenantBranding: "SELECT, UPDATE", // tenant admin edits branding (guarded by RBAC; row limited by app code)
  Subscription: "SELECT",
  TenantSetting: "SELECT, INSERT, UPDATE, DELETE",
  Permission: "SELECT",
  PlatformUser: "SELECT, UPDATE", // login + lastLoginAt/sessionVersion
  PlatformAuditLog: "SELECT, INSERT",
  _prisma_migrations: "SELECT",
};
for (const t of platformTables) {
  const g = platformGrants[t] ?? "SELECT";
  out.push(`GRANT ${g} ON "${t}" TO ${APP_ROLE};`);
}
// TenantSetting has tenantId but is a composite-id table → included above via tenantTables (has RLS). Nothing else to do.

process.stdout.write(out.join("\n") + "\n");
